-- regiones
CREATE TABLE regiones
  (
    id_region NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 5 PRIMARY KEY,
    region_nombre VARCHAR2( 50 ) NOT NULL
  );
-- paises table
CREATE TABLE paises
  (
    id_pais   CHAR( 2 ) PRIMARY KEY  ,
    pais_nombre VARCHAR2( 40 ) NOT NULL,
    id_region    NUMBER                 , -- fk
    CONSTRAINT fk_paises_regiones FOREIGN KEY( id_region )
      REFERENCES regiones( id_region ) 
      ON DELETE CASCADE
  );

-- location
CREATE TABLE ubicaciones
  (
    id_ubicacion NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 24 
                PRIMARY KEY       ,
    direccion     VARCHAR2( 255 ) NOT NULL,
    codigo_postal VARCHAR2( 20 )          ,
    ciudad        VARCHAR2( 50 )          ,
    estado       VARCHAR2( 50 )          ,
    id_pais  CHAR( 2 )               , -- fk
    CONSTRAINT fk_ubicaciones_paises 
      FOREIGN KEY( id_pais )
      REFERENCES paises( id_pais ) 
      ON DELETE CASCADE
  );
-- depositos
CREATE TABLE depositos
  (
    id_deposito NUMBER 
                 GENERATED BY DEFAULT AS IDENTITY START WITH 10 
                 PRIMARY KEY,
    deposito_nombre VARCHAR( 255 ) ,
    id_ubicacion    NUMBER( 12, 0 ), -- fk
    CONSTRAINT fk_depositos_ubicaciones 
      FOREIGN KEY( id_ubicacion )
      REFERENCES ubicaciones( id_ubicacion ) 
      ON DELETE CASCADE
  );
-- empleados
CREATE TABLE empleados
  (
    id_empleado NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 108 
                PRIMARY KEY,
    nombre VARCHAR( 255 ) NOT NULL,
    apellido  VARCHAR( 255 ) NOT NULL,
    email      VARCHAR( 255 ) NOT NULL,
    movil      VARCHAR( 50 ) NOT NULL ,
    alta  DATE NOT NULL          ,
    id_manager NUMBER( 12, 0 )        , -- fk
    puesto  VARCHAR( 255 ) NOT NULL,
    CONSTRAINT fk_empleados_manager 
        FOREIGN KEY( id_manager )
        REFERENCES empleados( id_empleado )
        ON DELETE CASCADE
  );
-- product category
CREATE TABLE categoria_productos
  (
    id_categoria NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 6 
                PRIMARY KEY,
    categoria_nombre VARCHAR2( 255 ) NOT NULL
  );

-- productos table
CREATE TABLE productos
  (
    id_producto NUMBER 
               GENERATED BY DEFAULT AS IDENTITY START WITH 289 
               PRIMARY KEY,
    producto_nombre  VARCHAR2( 255 ) NOT NULL,
    descripcion   VARCHAR2( 2000 )        ,
    costo_estandar NUMBER( 9, 2 )          ,
    precio_lista    NUMBER( 9, 2 )          ,
    id_categoria   NUMBER NOT NULL         ,
    CONSTRAINT fk_productos_categories 
      FOREIGN KEY( id_categoria )
      REFERENCES categoria_productos( id_categoria ) 
      ON DELETE CASCADE
  );
-- clientes
CREATE TABLE clientes
  (
    id_clientes NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 320 
                PRIMARY KEY,
    nombre         VARCHAR2( 255 ) NOT NULL,
    direccion      VARCHAR2( 255 )         ,
    pagina_web      VARCHAR2( 255 )         ,
    limite_credito NUMBER( 8, 2 )
  );
-- contactos
CREATE TABLE contactos
  (
    id_contacto NUMBER 
               GENERATED BY DEFAULT AS IDENTITY START WITH 320 
               PRIMARY KEY,
    nombre  VARCHAR2( 255 ) NOT NULL,
    apellido   VARCHAR2( 255 ) NOT NULL,
    email       VARCHAR2( 255 ) NOT NULL,
    movil       VARCHAR2( 20 )          ,
    id_clientes NUMBER                  ,
    CONSTRAINT fk_contactos_clientes 
      FOREIGN KEY( id_clientes )
      REFERENCES clientes( id_clientes ) 
      ON DELETE CASCADE
  );
-- ordenes table
CREATE TABLE ordenes
  (
    id_orden NUMBER 
             GENERATED BY DEFAULT AS IDENTITY START WITH 106 
             PRIMARY KEY,
    id_clientes NUMBER( 6, 0 ) NOT NULL, -- fk
    estado_orden      VARCHAR( 20 ) NOT NULL ,
    id_vendedor NUMBER( 6, 0 )         , -- fk
    fecha_orden  DATE NOT NULL          ,
    CONSTRAINT fk_ordenes_clientes 
      FOREIGN KEY( id_clientes )
      REFERENCES clientes( id_clientes )
      ON DELETE CASCADE,
    CONSTRAINT fk_ordenes_empleados 
      FOREIGN KEY( id_vendedor )
      REFERENCES empleados( id_empleado ) 
      ON DELETE SET NULL
  );
-- order items
CREATE TABLE items_orden
  (
    id_orden   NUMBER( 12, 0 )                                , -- fk
    id_item    NUMBER( 12, 0 )                                ,
    id_producto NUMBER( 12, 0 ) NOT NULL                       , -- fk
    cantidad   NUMBER( 8, 2 ) NOT NULL                        ,
    precio_unitario NUMBER( 8, 2 ) NOT NULL                        ,
    CONSTRAINT pk_items_orden 
      PRIMARY KEY( id_orden, id_item ),
    CONSTRAINT fk_items_orden_productos 
      FOREIGN KEY( id_producto )
      REFERENCES productos( id_producto ) 
      ON DELETE CASCADE,
    CONSTRAINT fk_items_orden_ordenes 
      FOREIGN KEY( id_orden )
      REFERENCES ordenes( id_orden ) 
      ON DELETE CASCADE
  );
-- inventarios
CREATE TABLE inventarios
  (
    id_producto   NUMBER( 12, 0 )        , -- fk
    id_deposito NUMBER( 12, 0 )        , -- fk
    cantidad     NUMBER( 8, 0 ) NOT NULL,
    CONSTRAINT pk_inventarios 
      PRIMARY KEY( id_producto, id_deposito ),
    CONSTRAINT fk_inventarios_productos 
      FOREIGN KEY( id_producto )
      REFERENCES productos( id_producto ) 
      ON DELETE CASCADE,
    CONSTRAINT fk_inventarios_depositos 
      FOREIGN KEY( id_deposito )
      REFERENCES depositos( id_deposito ) 
      ON DELETE CASCADE
  );